<?php

/**
 * peanutPageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginpeanutPageTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object peanutPageTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('peanutPage');
  }

  /**
   * Retrieves pages object.
   *
   * @param  string|int $item     The id or slug of item
   *
   * @return peanutPage
   */
  public function getItem($lang = null)
  {
    $p = $this->createQuery('p')
            ->leftJoin('p.translation t')
            ->leftJoin('p.sfGuardUser s')
            ->leftJoin('p.peanutMenu m')
            ->leftJoin('p.peanutSeo o')
            ->orderBy('p.position ASC');
    
    if(null !== $lang)
    {
      $p->where('t.lang = ?', $lang);
    }
    
    return $p;
  }

  /**
   * Retrieves pages object.
   *
   * @param  string|int $item     The id or slug of item
   *
   * @return peanutPage
   */
  public function showItem($item, $lang = null)
  {
    $p = $this->getItem($lang)
            ->andWhere('p.id = ? OR t.slug = ?', array($item, $item));

    return $p;
  }
  
  /**
   * Retrieves pages object.
   *
   * @param  string     $status   The status of items
   *
   * @return peanutPage
   */
  public function getItems($status = 'publish', $lang = null)
  {
    $p = $this->getItem($lang)
            ->andWhere('p.status = ?', $status);;

    return $p;
  }

  /**
   * Retrieves pages object by menu.
   *
   * @param  string|int $menu     The id or slug of menu
   *
   * @return peanutPage
   */
  public function getItemsByMenu($menu, $lang = null)
  {
    $p = $this->getItem($lang)
            ->andWhere('m.id = ? OR m.slug = ?', array($menu, $menu));

    return $p;
  }

  /**
   * Retrieves pages object by menu and status.
   *
   * @param  string|int $menu     The id or slug of menu
   * @param  string     $status   The status of page
   *
   * @return peanutPage
   */
  public function getItemsByMenuAndStatus($menu, $status = 'publish', $lang = null)
  {
    $p = $this->getItemsByMenu($menu)
            ->andWhere('p.status = ?', $status);

    return $p;
  }

  /**
   * Retrieves pages object by author.
   *
   * @param  string|int $author   The id or username of author
   * @param  string     $status   The status of page
   *
   * @return peanutPage
   */
  public function getItemsByAuthor($author, $lang = null)
  {
    $p = $this->getItem($lang)
            ->andWhere('s.id = ? OR s.username = ?', array($author, $author));

    return $p;
  }

  /**
   * Retrieves pages object by author.
   *
   * @param  string|int $author   The id or username of author
   * @param  string     $status   The status of page
   *
   * @return peanutPage
   */
  public function getItemsByAuthorAndStatus($author, $status = 'publish', $lang = null)
  {
    $p = $this->getItemsByAuthor($author)
            ->andWhere('p.status = ?', $status);

    return $p;
  }
}