<?php

/**
 * peanutLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginpeanutLinkTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object peanutLinkTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('peanutLink');
  }

  /**
   * Retrieves link object.
   *
   * @return peanutLink
   */
  public function getItem($lang = null)
  {
    $p = $this->createQuery('p')
            ->leftJoin('p.Translation t')
            ->leftJoin('p.sfGuardUser s')
            ->leftJoin('p.peanutMenu m')
            ->leftJoin('p.peanutXfn x')
            ->leftJoin('p.peanutSeo o')
            ->select('p.id, p.type, p.menu, p.author, p.status, p.url, p.relation, p.created_at, p.updated_at, p.position, p.seo_id')
            ->addSelect('t.title, t.content, t.excerpt, t.lang, t.slug')
            ->addSelect('s.id, s.first_name, s.last_name, s.email_address, s.username')
            ->addSelect('m.id, m.name, m.slug')
            ->addSelect('x.id, x.me, x.friendship, x.physical, x.professional, x.geographical, x.family, x.romantic')
            ->addSelect('o.id, o.title, o.description, o.keywords, o.is_indexable, o.is_followable')
            ->orderBy('p.position ASC');
    
    if(null !== $lang)
    {
      $p->andWhere('t.lang = ?', $lang);
    }
    
    return $p;
  }

  /**
   * Retrieves link object.
   *
   * @param  string|int $item     The id or slug of item
   *
   * @return peanutLink
   */
  public function showItem($item, $lang = null)
  {
    $p = $this->getItem($lang)
            ->andWhere('p.id = ? or t.slug = ?', array($item, $item));

    return $p;
  }

  /**
   * Retrieves link object.
   *
   * @param  string     $status   The status of items
   *
   * @return peanutLink
   */
  public function getItems($status = 'publish', $lang = null)
  {
    $p = $this->getItem($lang)
            ->andWhere('p.status = ?', $status);

    return $p;
  }

  /**
   * Retrieves links object by menu.
   *
   * @param  string|int $menu     The id or slug of menu
   * @param  string     $status   The status of items
   *
   * @return peanutLink
   */
  public function getItemsByMenu($menu, $status = 'publish', $lang = null)
  {
    $p = $this->getItems($status, $lang)
            ->andWhere('m.id = ? OR m.slug = ?', array($menu, $menu));

    return $p;
  }

  /**
   * Retrieves links object by author.
   *
   * @param  string|int $author     The id or username of user
   * @param  string     $status   The status of items
   *
   * @return peanutLink
   */
  public function getItemsByAuthor($author, $status = 'publish', $lang = null)
  {
    $p = $this->getItems($status, $lang)
            ->andWhere('s.id = ? OR s.username = ?', array($author, $author));

    return $p;
  }

  /**
   * Retrieves links object by relation.
   *
   * @param  string     $rel      The relation of item
   * @param  string     $status   The status of items
   *
   * @return peanutLink
   */
   public function getItemsByRelation($rel, $status = 'publish', $lang = null)
   {
     $p = $this->getItems($status, $lang)
             ->andWhere('x.me LIKE ?', '%' . $rel . '%')
             ->orWhere('x.friendship LIKE ?', '%' . $rel . '%')
             ->orWhere('x.physical LIKE ?', '%' . $rel . '%')
             ->orWhere('x.professional LIKE ?', '%' . $rel . '%')
             ->orWhere('x.geographical LIKE ?', '%' . $rel . '%')
             ->orWhere('x.family LIKE ?', '%' . $rel . '%')
             ->orWhere('x.romantic LIKE ?', '%' . $rel . '%')
             ->orderBy('p.position ASC');

     return $p;
   }
}