<?php

/**
 * peanutPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    peanutCorporatePlugin
 * @subpackage model
 * @author     Alexandre "pocky" Balmes <albalmes@gmail.com> <albalmes@gmail.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class PluginpeanutPage extends BasepeanutPage
{
  public function asArray()
  {
    return array(
        'id'          => $this->getId(),
        'slug'        => $this->getSlug(),
        'title'       => $this->getTitle(),
        'excerpt'     => $this->getExcerpt(),
        'content'     => $this->getContent(),
        'author'      => $this->getSfGuardUser()->getName(),
        'created_at'  => $this->getCreatedAt(),
        'updated_at'  => $this->getUpdatedAt()
    );
  }
}
